model:
  name: "ConvLSTM"
  params:
    history_steps: 5
    state_dict_path: "/bask/projects/v/vjgo8416-climate/shared/cloudcasting-validation/ocf-convLSTM/src/ocf_convLSTM/conv-lstm1-SD.pt"
validation:
  data_path: "/bask/projects/v/vjgo8416-climate/shared/data/eumetsat/testing2022/2022_test_nonhrv.zarr"
  wandb_project_name: "cloudcasting"
  wandb_run_name: "ConvLSTM-validation_50_batchlimit"
  nan_to_num: True
  batch_size: 16
  num_workers: 36
  batch_limit: 50
